# Generated by Django 2.2.24 on 2023-10-07 14:56

from django.db import migrations

def fill_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    flats.filter(construction_year__gte=2015).update(new_building=True)
    flats.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20231006_1731'),
    ]

    operations = [
        migrations.RunPython(fill_new_building)
    ]
