# Generated by Django 2.2.24 on 2023-10-09 15:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owners_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None, verbose_name='Номер владельца'),
        ),
    ]
