# Generated by Django 2.2.24 on 2023-10-10 16:56

from django.db import migrations

def from_flat_to_owner(apps, schema_editor):
    """Transfer owner data from Flat model to Owner"""
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()

    for flat in flats.iterator():
        Owner.objects.get_or_create(
            name=flat.owner,
            owner_pure_phone=flat.owner_pure_phone,
            defaults={
                'owners_phonenumber': flat.owners_phonenumber
            }
        )



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_owner'),
    ]

    operations = [
        migrations.RunPython(from_flat_to_owner)
    ]
