# Generated by Django 2.2.24 on 2023-10-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20231012_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='owner_phone',
        ),
    ]
